/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Current and new password */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_auth.ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Login credentials */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_auth.LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_auth.LoginResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current user from all devices */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Refresh token */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_auth.RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_auth.RefreshResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Registration data */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_auth.RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_auth.RegisterResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend email verification code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Email and optional locale */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_auth.ResendVerificationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm password reset code */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Email and code */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_auth.ResetPasswordConfirmReq"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Email */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_auth.ResetPasswordRequestReq"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set new password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Email, code and new password */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_auth.ResetPasswordSetReq"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Email and verification code */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_auth.VerifyEmailRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories */
        get: {
            parameters: {
                query?: {
                    /** @description Locale (en or ru, default en) */
                    locale?: "en" | "ru";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_categories.ListResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get category by ID */
        get: {
            parameters: {
                query?: {
                    /** @description Locale (en or ru, default en) */
                    locale?: "en" | "ru";
                };
                header?: never;
                path: {
                    /** @description Category UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_categories.SingleResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all cities */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_city.ListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contact-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send contact form message */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Contact message */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_contact.CreateRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_contact.SingleResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List items catalog */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default: 1) */
                    page?: number;
                    /** @description Items per page (default: 20, max: 100) */
                    per_page?: number;
                    /** @description Filter by category UUID */
                    category_id?: string;
                    /** @description Filter by one or more category UUIDs, comma-separated */
                    category_ids?: string;
                    /** @description Filter by city UUID */
                    city_uuid?: string;
                    /** @description Filter by GeoNames ID (alternative to city_uuid) */
                    geoname_id?: number;
                    /** @description Filter by condition */
                    condition?: "new" | "used";
                    /** @description Min price in minor units */
                    price_min?: number;
                    /** @description Max price in minor units */
                    price_max?: number;
                    /** @description Filter by seller UUID */
                    seller_id?: string;
                    /** @description Search by title */
                    search?: string;
                    /** @description Comma-separated statuses (e.g. published,archived). Non-published only allowed for own seller profile. */
                    statuses?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_item.ItemListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create item
         * @description Any authenticated user can create an item. Status is immediately 'published' (no moderation in MVP). Optional thumbnail_id sets the cover image from any uploaded item photo (independent of photo_ids).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Item data */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_item.CreateItemRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_item.ItemSingleResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List favorites */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (default: 1) */
                    page?: number;
                    /** @description Items per page (default: 20) */
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_favorite.FavoritesListResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** Add item to favorites */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Item ID */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_favorite.AddRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/favorites/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove item from favorites */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Item ID */
                    item_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get item by ID or slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Item UUID or slug */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_item.ItemSingleResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete item
         * @description Creator or admin can delete.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Item UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update item
         * @description Creator or admin can update. Admins are identified by ROLE_ADMIN in their JWT. The thumbnail_id is independent of photo_ids and can reference any uploaded item photo. To clear thumbnail, send thumbnail_id=null.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Item UUID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description Fields to update */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_item.UpdateItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_item.ItemSingleResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a payment */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_payment.CreatePaymentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_payment.CreatePaymentResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/webhooks/yookassa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook for YooKassa payment notifications */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_payment.WebhookResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a file */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * @description Upload target
                         * @enum {string}
                         */
                        type: "item" | "avatar";
                        /** @description Optional item UUID when type=item; if omitted, the upload is created without an associated item */
                        item_id?: string;
                        /**
                         * Format: binary
                         * @description Image file
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_upload.UploadResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user info */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_user.MeResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete current user account */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Current password confirmation */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_user.DeleteMeRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update current user profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Profile data */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_user.UpdateMeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_user.MeResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/chat/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List conversations for authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_chat.ConversationResponse"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Open or get a conversation with a user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Request */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_api_chat.OpenConversationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_chat.ConversationResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List messages in a conversation */
        get: {
            parameters: {
                query?: {
                    /** @description Message created_at for keyset pagination */
                    before?: string;
                    /** @description Limit (default 50, max 100) */
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Conversation ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_chat.MessageResponse"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Send a message (text and/or attachment) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Conversation ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** @description Message body */
                        body?: string;
                        /**
                         * Format: binary
                         * @description Attachment file
                         */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_chat.MessageResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/conversations/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark conversation as read */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Conversation ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/conversations/{id}/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** WebSocket connection for real-time chat */
        get: {
            parameters: {
                query: {
                    /** @description Access token */
                    token: string;
                };
                header?: never;
                path: {
                    /** @description Conversation ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Switching Protocols */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/unread-total": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get total count of conversations with unread messages */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: number;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Get API health status
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api_health.HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "github_com_dionisvl_avi_api-go_internal_api.PaginationResponse": {
            page?: number;
            per_page?: number;
            total?: number;
            total_pages?: number;
        };
        "github_com_dionisvl_avi_api-go_internal_api.ProblemDetails": {
            code?: string;
            detail?: string;
            status?: number;
            title?: string;
        };
        "github_com_dionisvl_avi_api-go_internal_api_item.CategoryResponse": {
            id?: string;
            name?: string;
            slug?: string;
        };
        "github_com_dionisvl_avi_api-go_internal_api_item.CityResponse": {
            geoname_id?: number;
            id?: string;
            is_active?: boolean;
            names?: {
                [key: string]: string;
            };
            population?: number;
            slug?: string;
        };
        "github_com_dionisvl_avi_api-go_internal_api_item.ItemResponse": {
            category?: components["schemas"]["github_com_dionisvl_avi_api-go_internal_api_item.CategoryResponse"];
            category_id?: string;
            city?: components["schemas"]["github_com_dionisvl_avi_api-go_internal_api_item.CityResponse"];
            condition?: string;
            created_at?: string;
            description?: string;
            id?: string;
            is_favorited?: boolean;
            photos?: components["schemas"]["github_com_dionisvl_avi_api-go_internal_api_item.PhotoResponse"][];
            price?: components["schemas"]["github_com_dionisvl_avi_api-go_internal_api_item.PriceResponse"];
            seller?: components["schemas"]["github_com_dionisvl_avi_api-go_internal_api_item.SellerResponse"];
            slug?: string;
            status?: string;
            tags?: string[];
            thumbnail?: components["schemas"]["github_com_dionisvl_avi_api-go_internal_api_item.PhotoResponse"];
            title?: string;
        };
        "github_com_dionisvl_avi_api-go_internal_api_item.PhotoResponse": {
            id?: string;
            thumbnail_url?: string;
            url?: string;
        };
        "github_com_dionisvl_avi_api-go_internal_api_item.PriceResponse": {
            amount?: number;
            currency?: string;
        };
        "github_com_dionisvl_avi_api-go_internal_api_item.SellerResponse": {
            id?: string;
            name?: string;
        };
        "github_com_dionisvl_avi_api-go_internal_model.UserPreferences": {
            /** @description UUID string */
            category_id?: string;
            /** @description UUID string */
            city_id?: string;
            condition?: string;
            price_max?: number;
            price_min?: number;
            search?: string;
        };
        "internal_api_auth.ChangePasswordRequest": {
            current_password: string;
            new_password: string;
        };
        "internal_api_auth.LoginRequest": {
            /** @example test@example.com */
            email: string;
            /** @example password123 */
            password: string;
        };
        "internal_api_auth.LoginResponse": {
            access_token?: string;
            expires_in?: number;
            refresh_token?: string;
        };
        "internal_api_auth.RefreshRequest": {
            refresh_token: string;
        };
        "internal_api_auth.RefreshResponse": {
            access_token?: string;
            expires_in?: number;
            refresh_token?: string;
        };
        "internal_api_auth.RegisterRequest": {
            email: string;
            email_verified?: boolean;
            /** @enum {string} */
            locale?: "ru" | "en";
            password: string;
        };
        "internal_api_auth.RegisterResponse": {
            email?: string;
            id?: string;
            roles?: string[];
        };
        "internal_api_auth.ResendVerificationRequest": {
            email: string;
            /** @enum {string} */
            locale?: "ru" | "en";
        };
        "internal_api_auth.ResetPasswordConfirmReq": {
            code: string;
            email: string;
        };
        "internal_api_auth.ResetPasswordRequestReq": {
            email: string;
        };
        "internal_api_auth.ResetPasswordSetReq": {
            code: string;
            email: string;
            new_password: string;
        };
        "internal_api_auth.VerifyEmailRequest": {
            code: string;
            email: string;
        };
        "internal_api_categories.CategoryResponse": {
            id?: string;
            name?: string;
            names?: {
                [key: string]: string;
            };
            parent_id?: string;
            slug?: string;
            sort_order?: number;
        };
        "internal_api_categories.ListResponse": {
            data?: components["schemas"]["internal_api_categories.CategoryResponse"][];
        };
        "internal_api_categories.SingleResponse": {
            data?: components["schemas"]["internal_api_categories.CategoryResponse"];
        };
        "internal_api_chat.ConversationResponse": {
            id?: string;
            last_message_at?: string;
            last_message_has_photo?: boolean;
            last_message_preview?: string;
            peer_avatar_url?: string;
            peer_id?: string;
            peer_name?: string;
            peer_type?: string;
            unread_count?: number;
        };
        "internal_api_chat.MessageResponse": {
            attachment_mime?: string;
            attachment_size?: number;
            attachment_url?: string;
            body?: string;
            created_at?: string;
            id?: string;
            is_mine?: boolean;
            sender_id?: string;
            /** @description "sent" | "read"; present only for outgoing messages */
            status?: string;
        };
        "internal_api_chat.OpenConversationRequest": {
            peer_user_id: string;
        };
        "internal_api_city.ListResponse": {
            data?: components["schemas"]["github_com_dionisvl_avi_api-go_internal_api_item.CityResponse"][];
        };
        "internal_api_contact.CreateRequest": {
            email: string;
            message: string;
            name: string;
            subject?: string;
        };
        "internal_api_contact.CreateResponse": {
            status?: string;
        };
        "internal_api_contact.SingleResponse": {
            data?: components["schemas"]["internal_api_contact.CreateResponse"];
        };
        "internal_api_favorite.AddRequest": {
            item_id: string;
        };
        "internal_api_favorite.FavoriteItemResponse": {
            created_at?: string;
            id?: string;
            item?: components["schemas"]["github_com_dionisvl_avi_api-go_internal_api_item.ItemResponse"];
            item_id?: string;
        };
        "internal_api_favorite.FavoritesListResponse": {
            data?: components["schemas"]["internal_api_favorite.FavoriteItemResponse"][];
            pagination?: components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.PaginationResponse"];
        };
        /** @description Health check response */
        "internal_api_health.HealthResponse": {
            status?: string;
            version?: string;
        };
        "internal_api_item.CategoryResponse": {
            id?: string;
            name?: string;
            slug?: string;
        };
        "internal_api_item.CityResponse": {
            geoname_id?: number;
            id?: string;
            is_active?: boolean;
            names?: {
                [key: string]: string;
            };
            population?: number;
            slug?: string;
        };
        "internal_api_item.CreateItemRequest": {
            category_id: string;
            city_uuid?: string;
            /** @enum {string} */
            condition?: "new" | "used";
            description?: string;
            geoname_id?: number;
            photo_ids?: string[];
            price?: components["schemas"]["internal_api_item.PriceRequest"];
            tags?: string[];
            thumbnail_id?: string;
            title: string;
        };
        "internal_api_item.ItemListResponse": {
            data?: components["schemas"]["internal_api_item.ItemResponse"][];
            pagination?: components["schemas"]["github_com_dionisvl_avi_api-go_internal_api.PaginationResponse"];
        };
        "internal_api_item.ItemResponse": {
            category?: components["schemas"]["internal_api_item.CategoryResponse"];
            category_id?: string;
            city?: components["schemas"]["internal_api_item.CityResponse"];
            condition?: string;
            created_at?: string;
            description?: string;
            id?: string;
            is_favorited?: boolean;
            photos?: components["schemas"]["internal_api_item.PhotoResponse"][];
            price?: components["schemas"]["internal_api_item.PriceResponse"];
            seller?: components["schemas"]["internal_api_item.SellerResponse"];
            slug?: string;
            status?: string;
            tags?: string[];
            thumbnail?: components["schemas"]["internal_api_item.PhotoResponse"];
            title?: string;
        };
        "internal_api_item.ItemSingleResponse": {
            data?: components["schemas"]["internal_api_item.ItemResponse"];
        };
        "internal_api_item.PhotoResponse": {
            id?: string;
            thumbnail_url?: string;
            url?: string;
        };
        "internal_api_item.PriceRequest": {
            amount?: number;
            currency: string;
        };
        "internal_api_item.PriceResponse": {
            amount?: number;
            currency?: string;
        };
        "internal_api_item.SellerResponse": {
            id?: string;
            name?: string;
        };
        "internal_api_item.UpdateItemRequest": {
            category_id?: string;
            city_uuid?: string;
            /** @enum {string} */
            condition?: "new" | "used";
            description?: string;
            geoname_id?: number;
            photo_ids?: string[];
            price?: components["schemas"]["internal_api_item.PriceRequest"];
            /** @enum {string} */
            status?: "published" | "draft" | "archived" | "sold";
            tags?: string[];
            thumbnail_id?: string;
            title?: string;
        };
        "internal_api_payment.AmountResponse": {
            currency?: string;
            value?: string;
        };
        "internal_api_payment.CreatePaymentRequest": {
            /** @enum {string} */
            purpose: "promote_listing" | "demo_checkout";
            return_url?: string;
            subject_id: string;
        };
        "internal_api_payment.CreatePaymentResponse": {
            amount?: components["schemas"]["internal_api_payment.AmountResponse"];
            confirmation_url?: string;
            id?: string;
            status?: string;
        };
        "internal_api_payment.WebhookResponse": {
            processed?: boolean;
        };
        "internal_api_upload.UploadData": {
            id?: string;
            thumbnail_url?: string;
            url?: string;
        };
        "internal_api_upload.UploadResponse": {
            data?: components["schemas"]["internal_api_upload.UploadData"];
        };
        "internal_api_user.DeleteMeRequest": {
            password: string;
        };
        "internal_api_user.MeResponse": {
            avatar_url?: string;
            created_at?: string;
            email?: string;
            email_verified?: boolean;
            has_profile?: boolean;
            id?: string;
            name?: string;
            preferences?: components["schemas"]["github_com_dionisvl_avi_api-go_internal_model.UserPreferences"];
            roles?: string[];
        };
        "internal_api_user.PreferencesRequest": {
            category_id?: string;
            city_id?: string;
            /** @enum {string} */
            condition?: "new" | "used";
            price_max?: number;
            price_min?: number;
            search?: string;
        };
        "internal_api_user.UpdateMeRequest": {
            name?: string;
            preferences?: components["schemas"]["internal_api_user.PreferencesRequest"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
