root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/api"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "docs", "tests"]
  include_ext = ["go", "toml", "env"]
  include_files = []
  rerun_delay = 500

[log]
  time = true

[misc]
  clean_on_exit = true
